apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"web-service","namespace":"myapp"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"web"}}}
  creationTimestamp: "2025-09-17T10:41:46Z"
  name: web-service
  namespace: myapp
  resourceVersion: "660033"
  uid: e9ecbf83-edd2-43dc-a68b-689466d59cec
spec:
  clusterIP: 10.96.104.91
  clusterIPs:
  - 10.96.104.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
